pg/app/routes.py
from datetime import datetime as dt

import requests
from flask import request, render_template, Blueprint, flash, redirect, url_for, abort, make_response
from flask_login import login_user, current_user, login_required, logout_user
from sqlalchemy.exc import IntegrityError

from .core import db, photos
from .forms import SignupForm, LoginForm, UploadImageForm
from .models import Photo, User
from .utils import get_image_np, coco_labels

from PIL import Image, ImageFont, ImageDraw, ImageEnhance
from werkzeug.datastructures import FileStorage
from io import BytesIO, StringIO
import csv

# Blueprint Configuration
main_bp = Blueprint('main_bp', __name__, template_folder='templates', static_folder='static')


@main_bp.route('/')
def index():
    return render_template('index.html')


@main_bp.route('/register', methods=['GET', 'POST'])
def register():
    form = SignupForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                new_user = User(form.username.data, form.email.data, dt.now(), False)
                new_user.set_password(form.password.data)
                new_user.authenticated = True
                db.session.add(new_user)
                db.session.commit()
                flash('Thanks for registering!', 'success')
                return redirect(url_for('main_bp.login'))
            except IntegrityError:
                db.session.rollback()
                flash('ERROR! Email ({}) already exists.'.format(form.email.data), 'error')
    return render_template('/auth/register.html', form=form)


@main_bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(email=form.email.data).first()
            if user is not None and user.check_password(form.password.data):
                user.authenticated = True
                db.session.add(user)
                db.session.commit()
                login_user(user)
                flash('Thanks for logging in, {}'.format(current_user.email))
                return redirect(url_for('main_bp.index'))
            else:
                flash('ERROR! Incorrect login credentials.', 'error')
    return render_template('/auth/login.html', form=form)


@main_bp.route('/logout')
@login_required
def logout():
    user = current_user
    user.authenticated = False
    db.session.add(user)
    db.session.commit()
    logout_user()
    flash('Goodbye!', 'info')
    return redirect(url_for('main_bp.login'))


def save_and_predict(file):
    filename = photos.save(file)
    url = photos.url(filename)
    path = photos.path(filename)
    payload = {"instances": [get_image_np(path).tolist()]}
    res = requests.post("http://serving:8080/v1/models/default:predict", json=payload)
    predictions = res.json().get('predictions')[0]
    num_detections = predictions.get('num_detections')
    num_detections = int(num_detections)
    detection_classes, detection_boxes, detection_scores = predictions.get('detection_classes')[:num_detections], \
                                                           predictions.get('detection_boxes')[:num_detections], \
                                                           predictions.get('detection_scores')[:num_detections]

    source_img = Image.open(photos.path(filename)).convert("RGB")
    width, height = source_img.size
    for idx, box in enumerate(detection_boxes):
        ymin, xmin, ymax, xmax = height * box[0], width * box[1], height * box[2], width * box[3]
        draw = ImageDraw.Draw(source_img)
        draw.rectangle(((xmin, ymin), (xmax, ymax)))
        draw.text((xmin, ymin),
                  "class: %s confidence %s" % (
                      coco_labels[int(detection_classes[idx])], str(round(detection_scores[idx], 2))))
    image_io = BytesIO()
    source_img.save(image_io, format="JPEG")
    image_io.seek(0)

    processed_filename = 'proccessed_' + filename
    image_storage = FileStorage(stream=image_io, filename=processed_filename)
    photos.save(image_storage)
    processed_url = photos.url(processed_filename)
    photo = Photo(current_user.id, image_filename=filename, image_url=url, num_detection=num_detections,
                  boxes=detection_boxes, classes=detection_classes, score=detection_scores,
                  processed_filename=processed_filename, processed_url=processed_url)
    db.session.add(photo)
    db.session.commit()
    flash('New image, {}, added!'.format(photo.image_filename), 'success')


@main_bp.route('/upload', methods=['GET', 'POST'])
@login_required
def upload():
    form = UploadImageForm()

    if request.method == 'POST':
        if form.validate_on_submit():
            file = request.files['animal_image']
            save_and_predict(file)
            return redirect(url_for('main_bp.show_all'))
        elif request.files:
            file_obj = request.files
            for f in file_obj:
                file = request.files.get(f)
                save_and_predict(file)
            return redirect(url_for('main_bp.show_all'))
        else:
            flash('ERROR! Image was not added.', 'error')
    return render_template('upload.html', form=form)


@main_bp.route('/show-all')
@login_required
def show_all():
    uid = current_user.id
    _photos = Photo.query.filter(Photo.user_id == int(uid)).all()

    if photos is None:
        abort(404)
    return render_template('my-upload.html', photos=_photos)


@main_bp.route("/get-results-csv")
@login_required
def get_results_csv():
    si = StringIO()
    fieldnames = ['file_name', 'class', 'num_detection', 'boxes', 'score']
    cw = csv.writer(si)
    cw.writerow(fieldnames)

    uid = current_user.id
    _photos = Photo.query.filter(Photo.user_id == int(uid)).all()
    for photo in _photos:
        file_name = photo.image_filename
        _class = photo.classes
        num_detection = photo.num_detection
        boxes = photo.boxes
        score = photo.score
        cw.writerow([file_name, _class, str(num_detection), boxes, score])
    output = make_response(si.getvalue())
    output.headers["Content-Disposition"] = "attachment; filename=results_for_%s.csv" % current_user.username
    output.headers["Content-type"] = "text/csv"
    return output


@main_bp.route("/get-image/<filename>")
@login_required
def get_image(filename):
    image_io = BytesIO()
    source_img = Image.open(photos.path(filename)).convert("RGB")
    source_img.save(image_io, format="JPEG")
    image_io.seek(0)
    response = make_response(image_io.getvalue())
    response.headers.set('Content-Type', 'image/jpeg')
    response.headers.set(
        'Content-Disposition', 'attachment', filename='%s.jpg' % filename)
    return response

pg/app/templates/_form_macros.html
{% macro render_field(field) %}


<dt>{{ field.label }}:

<dd>{{ field(**kwargs)|safe }}
	{% if field.errors %}
	<span class="error">
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
    </span>
	{% endif %}
</dd>


{% endmacro %}

pg/app/templates/base.html
<!doctype html>

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Demo of web prototype">
	<meta name="author" content="Charles Jing">
	<title>{% block title %}{% endblock %} - Flask Demo App</title>
	<!-- styles -->
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet"
	      integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
	<!-- child template -->
	{% block head %}
	{% endblock %}
</head>


<body>
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
	<div class="container">

		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
			        data-target="#recipes-navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{{ url_for('main_bp.index') }}">Flask Demo App</a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="recipes-navbar-collapse-1">
			<ul class="nav navbar-nav">
				{% if current_user.is_authenticated %}
				<li><a href="{{ url_for('main_bp.upload') }}">Upload Image</a></li>
				<li><a href="{{ url_for('main_bp.show_all', usr=current_user.username, uid=current_user.id) }}">My
					Uploads</a></li>
				{% endif %}
			</ul>
			<ul class="nav navbar-nav navbar-right">
				{% if current_user.is_authenticated %}
				<li><a href="#">{{ current_user.username }}</a>
				<li><a href="{{ url_for('main_bp.logout') }}">Log Out</a>
					{% else %}
				<li><a href="{{ url_for('main_bp.register') }}">Register</a>
				<li><a href="{{ url_for('main_bp.login') }}">Log In</a>
					{% endif %}
			</ul>
		</div><!--/.nav-collapse -->
	</div><!-- /.container -->
</nav>
<br>
<br>
<br>
<br>
{% for message in get_flashed_messages() %}
<div class="flash">{{ message }}</div>
{% endfor %}
<div class="container">
	<div class="content">

		<!-- child template -->
		{% block content %}
		{% endblock %}

	</div>
	<div class="footer">
		<hr>
		<p>Jing - 2020</p>
	</div>
</div><!-- /.container -->

<!-- scripts -->
<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
        integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
        crossorigin="anonymous"></script>
{% block script %}
{% endblock %}
</body>
</html>

pg/app/templates/index.html
{% extends "base.html" %}
{% block content %}

<center>
	<img src="{{ url_for('static', filename = 'lens.png') }}" width="240px" height="240px" class="center">
	<h1>Inception with COCO Online!</h1>
	<h4>Author: Zhihe Jing</h4>
	<h4>Email: cubric.mms@foxmail.com</h4>
	<h4>Date: 2020-05-08</h4>
</center>
{% endblock %}

pg/app/templates/my-upload.html
{% extends "base.html" %}
{% block content %}

<div class="user-profile">
	<div class="page-header">
		<h2 style="display: inline-block; width: 100%; margin-right: -50%;"> {{current_user.username}}'s uploads </h2>
		{% if photos %}
		<a href="{{ url_for('main_bp.get_results_csv') }}">
			<button class="btn btn-sm btn-info" type="button" style="float: right; margin-top:30px; margin-right:40px;">
				Download CSV
			</button>
		</a>
		{% endif %}
	</div>


	<div class="row">
		{% for photo in photos %}
		<div class="col-sm-5">
			<h4>Original: {{ photo.image_filename }}</h4>
			{% if photo.image_url %}
			<img src="{{ photo.image_url }}" alt="{{ photo }}" style="width: 100%; height: 100%; object-fit: contain;">
			{% endif %}
		</div>
		<div class="col-sm-5">
			<h4>Processed: {{ photo.processed_filename }}</h4>
			{% if photo.processed_url %}
			<img src="{{ photo.processed_url }}" alt="{{ photo }}"
			     style="width: 100%; height: 100%; object-fit: contain;">
			{% endif %}
		</div>
		<div class="col-sm-2">
			<a href="{{ url_for('main_bp.get_image', filename=photo.processed_filename) }}">
				<button class="btn btn-sm btn-info" type="button"
				        style=" margin-top: 150px; margin-left:20%;"> Download Image
				</button>
			</a>
		</div>
		{% endfor %}
	</div>
</div>

{% endblock %}

pg/app/templates/upload.html
{% extends "base.html" %}
{% from "_form_macros.html" import render_field %}

{% block head %}
{{ dropzone.load_css() }}
{{ dropzone.style('border: 2px dashed #0087F7; margin: 1%; min-height: 200px;') }}
{% endblock %}

{% block content %}


<div class="add-animal">
	<div class="page-header">
		<h2>Add a New Animal Image</h2>
	</div>

	<div class="row">
		<div class="col-sm-3">
			<form action="{{ url_for('main_bp.upload') }}" method="post" enctype="multipart/form-data">
				{{ form.csrf_token }}
				<dl>
					{{ render_field(form.animal_image) }}
				</dl>
				<button class="btn btn-sm btn-success" type="submit">Add Animal Image</button>
			</form>
		</div>
		<div class="col-sm-9">
			{{ dropzone.create(action='main_bp.upload') }}
		</div>
	</div>
</div>

{% endblock %}

{% block script %}
{{ dropzone.load_js() }}
{% endblock %}

{{ dropzone.config(redirect_url=url_for('main_bp.show_all', usr=current_user.username, uid=current_user.id)) }}